theme: jekyll-theme-minimal
title: CV | Nguyễn Công Khanh
description: Have experience in front-end Development about using NodeJS, NuxtJS, VueJS Framework and related libraries such as Vuetify, VueX, Vue-i18n, ElectronVue,…
